/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.macstab.duplicatefinder

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = DuplicateFinder()
        //assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
