#name: Create Multi-Architecture Docker Image
#
#on:
#  workflow_run:
#    workflows: ["Flash Duplicate Finder - Multi-Architecture Build with Jib and GraalVM"]
#    types:
#      - completed
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Create and push multi-arch Docker image
#        run: |
#          export DOCKER_CLI_EXPERIMENTAL=enabled
#          docker manifest create <your-docker-username>/<your-image-name>:<tag> <your-docker-username>/<your-image-name>:arm64 <your-docker-username>/<your-image-name>:amd64
#          docker manifest annotate <your-docker-username>/<your-image-name>:<tag> <your-docker-username>/<your-image-name>:arm64 --os linux --arch arm64
#          docker manifest annotate <your-docker-username>/<your-image-name>:<tag> <your-docker-username>/<your-image-name>:amd64 --os linux --arch amd64
#          docker manifest push <your-docker-username>/<your-image-name>:<tag>